### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by nikitinalexx** [snipplets/Dota-2-Building-Helper#3]
Is it possible  that you make a working .vmap example? The game does not show any warnings, function addbuilding and etc are called but nothing happens... my hero does not react to a command to build something.

**Comment by musshorn** [comment]
I'm not sure what you mean? the vmap file in `content/dota_addons/samplerts/maps` hasn't changed for a few months and still works fine?

**Comment by Soarick** [comment]
I had also just downloaded the building helper and when I built it, the hero (ancient apparition) could not build any structure.When I click on the skill to build arrow tower, it only allows me to move my mouse with the green overlay of the structure size and could not click again to build it.

**Comment by nikitinalexx** [comment]
snipplets, but how about an example with up to date changes? I think that .vmap is not even v2.1

**Comment by musshorn** [comment]
Try it with todays updates? I fixed a problem for people who don't have 1920x1080 monitors so it should work for all screen sizes now.

**Comment by thehobojoe** [comment]
Still not working properly for me, there is no grid or ghosts, and most clicks don't register to actually make the building. The ghost square also is not tied properly to the mouse, it goes further to the right than the mouse does the closer the mouse gets to the right side of the screen. 1920x1200 screen.

http://gfycat.com/CompleteSelfishAardwolf

**Comment by musshorn** [comment]
Thanks for the webm, I can't set my resolution higher than 1920x1080. Try this update and see how it goes?

**Comment by thehobojoe** [comment]
Behavior seems to be identical compared to before. The ghost slides further to the right, and buildings don't register most clicks or won't build anywhere near another building.

http://gfycat.com/UntidyEachBlackrussianterrier

**Comment by int128fly** [comment]
Hi,

I don't know how to private message you on github so I decided to communicate thru here (not the best place but w.e.) I really love the concept and the project and I was wondering if I can add you on steam. I am looking into your solution and I really like it, just want to encourage you and hope we get a stable fully working building logic system :+1:

**Comment by musshorn** [comment]
@thehobojoe Are you able to change lines 18-20 in `building_helper.js` to this? [gist](https://gist.github.com/snipplets/c83919a02eea5247876c)

Once that's in open vConsole and it should be getting spammed with an array (your fps will probably drop too) and move your mouse as far as you can to the right in game. Let me know what numbers you get.

@int128fly Thanks, The best help anyone can offer is coding! The code is there, it's open source. I'll accept any pull request that adds either reasonable features or fixes bugs. I work full time so I cant develop this as much as other people, but that's the whole point of open source. Everyone does their little bit and in the end you get an amazing product.
